version: '2.1'

services:

  metrics:
    build: ./application
    ports:
    - "8000:8000"
    - "8001:8001"

  prometheus:
    build: ./prometheus
    ports:
    - "9090:9090"
    restart: always
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --web.enable-lifecycle  # curl -X POST http://prometheus:8080/-/reload
